library(seqinr)
library(phangorn)
setwd("~/Desktop/")
fdir <- system.file("extdata/trees", package = "phangorn")
dpp <- read.phyDat(file = "clustalw.fasta", format = "fasta")
dm <- dist.ml(dpp)
treeUPGMA <- upgma(dm)
treeNJ <- NJ(dm)
layout(matrix(c(1,2), 2, 1), height=c(1,1))
par(mar = c(0,0,2,0)+ 0.1)
plot(treeUPGMA, main="UPGMA")
plot(treeNJ, "unrooted", main="NJ")
hh <- read.phyDat(file = "hedgehogAlign.fasta", format = "fasta")
dm <- dist.ml(hh)
treeUPGMA <- upgma(dm)
treeNJ <- NJ(dm)
layout(matrix(c(1,2), 2, 1), height=c(1,1))
par(mar = c(0,0,2,0)+ 0.1)
plot(treeUPGMA, main="UPGMA")
plot(treeNJ, "unrooted", main="NJ")
punt <- read.phyDat(file = "punt.fasta", format = "fasta" )
dm <- dist.ml(punt)
treeUPGMA <- upgma(dm)
treeNJ <- NJ(dm)
layout(matrix(c(1,2), 2, 1), height=c(1,1))
par(mar = c(0,0,2,0)+ 0.1)
plot(treeUPGMA, main="UPGMA")
plot(treeNJ, "unrooted", main="NJ")
